-- =====================================================================
-- Nuove carte: 85 carte (5 fazioni x 17 righe della tabella) al posto di tutto il catalogo attuale.
-- Eseguire nello SQL editor di Supabase, UN BLOCCO ALLA VOLTA, nell'ordine (1, 2, 3, 4).
-- Clownerie (giallo) non ha ancora carte: finché non le aggiungiamo non viene scelta nei mazzi.
-- =====================================================================

-- 1) ANTEPRIMA (non modifica niente): cosa verrà cancellato.
select f.code as fazione, c.card_type, count(*) as carte
from public.cards c left join public.factions f on f.id = c.faction_id
group by 1, 2 order by 1, 2;

-- 2) COPIA DI SICUREZZA. Le tabelle nuove in "public" sono leggibili dal browser di default:
--    la riga "enable row level security" senza policy le chiude a tutti tranne che a te nel pannello.
create table public.cards_backup_20261006 as table public.cards;
alter table public.cards_backup_20261006 enable row level security;
create table public.card_subtype_links_backup_20261006 as table public.card_subtype_links;
alter table public.card_subtype_links_backup_20261006 enable row level security;

-- 3) CANCELLAZIONE DELLE CARTE VECCHIE (tutte, Mostrissimi e boss compresi) E INSERIMENTO DELLE NUOVE.
--    Un unico blocco: se qualcosa va storto non cambia niente. Le tabelle che puntano alle carte
--    (collegamenti ai sottotipi, ecc.) vengono svuotate dalle sole righe collegate, trovate in automatico.
do $$
declare r record;
begin
  for r in
    select c.conrelid::regclass as child, a.attname as col
    from pg_constraint c
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = c.conkey[1]
    where c.contype = 'f' and c.confrelid = 'public.cards'::regclass and c.conrelid <> 'public.cards'::regclass
  loop
    execute format('delete from %s where %I in (select id from public.cards)', r.child, r.col);
  end loop;
  delete from public.cards;

  insert into public.cards
    (id, name, faction_id, card_type, mana_cost, attack, hp, effect_text, effect_json, effect_on_death_json,
     sacrifice_cost, rarity, keywords, flavor_text, subtype, image_url, is_boss, is_indrazzi)
  values
  (gen_random_uuid(), 'Benedizione · Maledizione 1', 1, 'maledizione', 1, null, null, 'Guadagni 2 punti vita', '{"type":"heal","amount":2,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Maledizione 2', 1, 'maledizione', 2, null, null, 'Guadagni 3 punti vita', '{"type":"heal","amount":3,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Maledizione 3', 1, 'maledizione', 3, null, null, 'Guadagni 4 punti vita', '{"type":"heal","amount":4,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Maledizione 4', 1, 'maledizione', 4, null, null, 'Guadagni 5 punti vita', '{"type":"heal","amount":5,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Maledizione 5', 1, 'maledizione', 5, null, null, 'Guadagni 6 punti vita', '{"type":"heal","amount":6,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Mostro 1', 1, 'monster', 1, 1, 1, 'Guadagni 1 punto vita', '{"type":"heal","amount":1,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Mostro 2', 1, 'monster', 2, 2, 2, 'Guadagni 1 punto vita', '{"type":"heal","amount":1,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Mostro 3', 1, 'monster', 3, 3, 3, 'Guadagni 2 punti vita', '{"type":"heal","amount":2,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Mostro 4', 1, 'monster', 4, 4, 4, 'Guadagni 2 punti vita', '{"type":"heal","amount":2,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Mostro 5', 1, 'monster', 5, 5, 5, 'Guadagni 3 punti vita', '{"type":"heal","amount":3,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Trappola 2', 1, 'instant', 2, null, null, 'Quando l''avversario gioca una carta dalla mano: Guadagni 2 punti vita', '{"effects":[{"type":"heal","amount":2,"target":"self","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Trappola 3', 1, 'instant', 3, null, null, 'Quando l''avversario gioca una carta dalla mano: Guadagni 3 punti vita', '{"effects":[{"type":"heal","amount":3,"target":"self","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Trappola 4', 1, 'instant', 4, null, null, 'Quando l''avversario gioca una carta dalla mano: Guadagni 4 punti vita', '{"effects":[{"type":"heal","amount":4,"target":"self","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Aura 1', 1, 'aura', 1, null, null, 'Ogni volta che la creatura attacca, guadagni 2 punti vita', '{"effects":[{"type":"heal","amount":2,"target":"self","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Aura 3', 1, 'aura', 3, null, null, 'Ogni volta che la creatura attacca, guadagni 3 punti vita', '{"effects":[{"type":"heal","amount":3,"target":"self","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Terraforma 3', 1, 'terraforma', 3, null, 3, 'Ogni volta che evochi un tuo mostro, guadagni 4 punti vita', '{"effects":[{"type":"heal","amount":4,"target":"self","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Benedizione · Terraforma 5', 1, 'terraforma', 5, null, 5, 'Ogni volta che evochi un tuo mostro, guadagni 5 punti vita', '{"effects":[{"type":"heal","amount":5,"target":"self","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Maledizione 1', 2, 'maledizione', 1, null, null, 'Pesca 2 carte', '{"type":"draw","amount":2,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Maledizione 2', 2, 'maledizione', 2, null, null, 'Pesca 3 carte', '{"type":"draw","amount":3,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Maledizione 3', 2, 'maledizione', 3, null, null, 'Pesca 4 carte', '{"type":"draw","amount":4,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Maledizione 4', 2, 'maledizione', 4, null, null, 'Pesca 5 carte', '{"type":"draw","amount":5,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Maledizione 5', 2, 'maledizione', 5, null, null, 'Pesca 6 carte', '{"type":"draw","amount":6,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Mostro 1', 2, 'monster', 1, 1, 1, 'Pesca 1 carta', '{"type":"draw","amount":1,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Mostro 2', 2, 'monster', 2, 2, 2, 'Pesca 1 carta', '{"type":"draw","amount":1,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Mostro 3', 2, 'monster', 3, 3, 3, 'Pesca 2 carte', '{"type":"draw","amount":2,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Mostro 4', 2, 'monster', 4, 4, 4, 'Pesca 2 carte', '{"type":"draw","amount":2,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Mostro 5', 2, 'monster', 5, 5, 5, 'Pesca 3 carte', '{"type":"draw","amount":3,"target":"self","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Trappola 2', 2, 'instant', 2, null, null, 'Quando l''avversario gioca una carta dalla mano: Pesca 2 carte', '{"effects":[{"type":"draw","amount":2,"target":"self","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Trappola 3', 2, 'instant', 3, null, null, 'Quando l''avversario gioca una carta dalla mano: Pesca 3 carte', '{"effects":[{"type":"draw","amount":3,"target":"self","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Trappola 4', 2, 'instant', 4, null, null, 'Quando l''avversario gioca una carta dalla mano: Pesca 4 carte', '{"effects":[{"type":"draw","amount":4,"target":"self","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Aura 1', 2, 'aura', 1, null, null, 'Ogni volta che la creatura attacca, pesca 2 carte', '{"effects":[{"type":"draw","amount":2,"target":"self","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Aura 3', 2, 'aura', 3, null, null, 'Ogni volta che la creatura attacca, pesca 3 carte', '{"effects":[{"type":"draw","amount":3,"target":"self","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Terraforma 3', 2, 'terraforma', 3, null, 3, 'Ogni volta che evochi un tuo mostro, pesca 4 carte', '{"effects":[{"type":"draw","amount":4,"target":"self","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Intuizione · Terraforma 5', 2, 'terraforma', 5, null, 5, 'Ogni volta che evochi un tuo mostro, pesca 5 carte', '{"effects":[{"type":"draw","amount":5,"target":"self","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Maledizione 1', 3, 'maledizione', 1, null, null, 'L''avversario scarta 2 carte a caso', '{"type":"discard","amount":2,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Maledizione 2', 3, 'maledizione', 2, null, null, 'L''avversario scarta 3 carte a caso', '{"type":"discard","amount":3,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Maledizione 3', 3, 'maledizione', 3, null, null, 'L''avversario scarta 4 carte a caso', '{"type":"discard","amount":4,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Maledizione 4', 3, 'maledizione', 4, null, null, 'L''avversario scarta 5 carte a caso', '{"type":"discard","amount":5,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Maledizione 5', 3, 'maledizione', 5, null, null, 'L''avversario scarta 6 carte a caso', '{"type":"discard","amount":6,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Mostro 1', 3, 'monster', 1, 1, 1, 'L''avversario scarta 1 carta a caso', '{"type":"discard","amount":1,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Mostro 2', 3, 'monster', 2, 2, 2, 'L''avversario scarta 1 carta a caso', '{"type":"discard","amount":1,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Mostro 3', 3, 'monster', 3, 3, 3, 'L''avversario scarta 2 carte a caso', '{"type":"discard","amount":2,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Mostro 4', 3, 'monster', 4, 4, 4, 'L''avversario scarta 2 carte a caso', '{"type":"discard","amount":2,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Mostro 5', 3, 'monster', 5, 5, 5, 'L''avversario scarta 3 carte a caso', '{"type":"discard","amount":3,"target":"opponent","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Trappola 2', 3, 'instant', 2, null, null, 'Quando l''avversario gioca una carta dalla mano: L''avversario scarta 2 carte a caso', '{"effects":[{"type":"discard","amount":2,"target":"opponent","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Trappola 3', 3, 'instant', 3, null, null, 'Quando l''avversario gioca una carta dalla mano: L''avversario scarta 3 carte a caso', '{"effects":[{"type":"discard","amount":3,"target":"opponent","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Trappola 4', 3, 'instant', 4, null, null, 'Quando l''avversario gioca una carta dalla mano: L''avversario scarta 4 carte a caso', '{"effects":[{"type":"discard","amount":4,"target":"opponent","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Aura 1', 3, 'aura', 1, null, null, 'Ogni volta che la creatura attacca, L''avversario scarta 2 carte a caso', '{"effects":[{"type":"discard","amount":2,"target":"opponent","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Aura 3', 3, 'aura', 3, null, null, 'Ogni volta che la creatura attacca, L''avversario scarta 3 carte a caso', '{"effects":[{"type":"discard","amount":3,"target":"opponent","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Terraforma 3', 3, 'terraforma', 3, null, 3, 'Ogni volta che evochi un tuo mostro, L''avversario scarta 4 carte a caso', '{"effects":[{"type":"discard","amount":4,"target":"opponent","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Contagio · Terraforma 5', 3, 'terraforma', 5, null, 5, 'Ogni volta che evochi un tuo mostro, L''avversario scarta 5 carte a caso', '{"effects":[{"type":"discard","amount":5,"target":"opponent","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Maledizione 1', 4, 'maledizione', 1, null, null, 'Infliggi 2 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":2,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Maledizione 2', 4, 'maledizione', 2, null, null, 'Infliggi 3 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":3,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Maledizione 3', 4, 'maledizione', 3, null, null, 'Infliggi 4 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":4,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Maledizione 4', 4, 'maledizione', 4, null, null, 'Infliggi 5 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":5,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Maledizione 5', 4, 'maledizione', 5, null, null, 'Infliggi 6 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":6,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Mostro 1', 4, 'monster', 1, 1, 1, 'Infliggi 1 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":1,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Mostro 2', 4, 'monster', 2, 2, 2, 'Infliggi 1 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":1,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Mostro 3', 4, 'monster', 3, 3, 3, 'Infliggi 2 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":2,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Mostro 4', 4, 'monster', 4, 4, 4, 'Infliggi 2 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":2,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Mostro 5', 4, 'monster', 5, 5, 5, 'Infliggi 3 danno a un bersaglio a tua scelta (avversario o creatura)', '{"type":"damage","amount":3,"target":"any_target","timing":"on_play"}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Trappola 2', 4, 'instant', 2, null, null, 'Quando l''avversario gioca una carta dalla mano: Infliggi 2 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":2,"target":"any_target","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Trappola 3', 4, 'instant', 3, null, null, 'Quando l''avversario gioca una carta dalla mano: Infliggi 3 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":3,"target":"any_target","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Trappola 4', 4, 'instant', 4, null, null, 'Quando l''avversario gioca una carta dalla mano: Infliggi 4 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":4,"target":"any_target","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Aura 1', 4, 'aura', 1, null, null, 'Ogni volta che la creatura attacca, infliggi 2 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":2,"target":"any_target","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Aura 3', 4, 'aura', 3, null, null, 'Ogni volta che la creatura attacca, infliggi 3 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":3,"target":"any_target","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Terraforma 3', 4, 'terraforma', 3, null, 3, 'Ogni volta che evochi un tuo mostro, infliggi 4 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":4,"target":"any_target","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Prepotenza · Terraforma 5', 4, 'terraforma', 5, null, 5, 'Ogni volta che evochi un tuo mostro, infliggi 5 danno a un bersaglio a tua scelta (avversario o creatura)', '{"effects":[{"type":"damage","amount":5,"target":"any_target","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Maledizione 1', 5, 'maledizione', 1, null, null, 'Una creatura ottiene +2/+2', '{"effects":[{"type":"buff","stat":"attack","amount":2,"target":"any_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":2,"target":"any_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Maledizione 2', 5, 'maledizione', 2, null, null, 'Una creatura ottiene +3/+3', '{"effects":[{"type":"buff","stat":"attack","amount":3,"target":"any_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":3,"target":"any_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Maledizione 3', 5, 'maledizione', 3, null, null, 'Una creatura ottiene +4/+4', '{"effects":[{"type":"buff","stat":"attack","amount":4,"target":"any_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":4,"target":"any_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Maledizione 4', 5, 'maledizione', 4, null, null, 'Una creatura ottiene +5/+5', '{"effects":[{"type":"buff","stat":"attack","amount":5,"target":"any_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":5,"target":"any_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Maledizione 5', 5, 'maledizione', 5, null, null, 'Una creatura ottiene +6/+6', '{"effects":[{"type":"buff","stat":"attack","amount":6,"target":"any_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":6,"target":"any_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Mostro 1', 5, 'monster', 1, 1, 1, 'Questa creatura ottiene +1/+1', '{"effects":[{"type":"buff","stat":"attack","amount":1,"target":"source_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":1,"target":"source_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Mostro 2', 5, 'monster', 2, 2, 2, 'Questa creatura ottiene +1/+1', '{"effects":[{"type":"buff","stat":"attack","amount":1,"target":"source_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":1,"target":"source_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Mostro 3', 5, 'monster', 3, 3, 3, 'Questa creatura ottiene +2/+2', '{"effects":[{"type":"buff","stat":"attack","amount":2,"target":"source_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":2,"target":"source_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Mostro 4', 5, 'monster', 4, 4, 4, 'Questa creatura ottiene +2/+2', '{"effects":[{"type":"buff","stat":"attack","amount":2,"target":"source_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":2,"target":"source_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Mostro 5', 5, 'monster', 5, 5, 5, 'Questa creatura ottiene +3/+3', '{"effects":[{"type":"buff","stat":"attack","amount":3,"target":"source_creature","duration":"permanent","timing":"on_play"},{"type":"buff","stat":"hp","amount":3,"target":"source_creature","duration":"permanent","timing":"on_play"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Trappola 2', 5, 'instant', 2, null, null, 'Quando l''avversario gioca una carta dalla mano: Una creatura ottiene +2/+2', '{"effects":[{"type":"buff","stat":"attack","amount":2,"target":"any_creature","duration":"permanent","timing":"instant"},{"type":"buff","stat":"hp","amount":2,"target":"any_creature","duration":"permanent","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Trappola 3', 5, 'instant', 3, null, null, 'Quando l''avversario gioca una carta dalla mano: Una creatura ottiene +3/+3', '{"effects":[{"type":"buff","stat":"attack","amount":3,"target":"any_creature","duration":"permanent","timing":"instant"},{"type":"buff","stat":"hp","amount":3,"target":"any_creature","duration":"permanent","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Trappola 4', 5, 'instant', 4, null, null, 'Quando l''avversario gioca una carta dalla mano: Una creatura ottiene +4/+4', '{"effects":[{"type":"buff","stat":"attack","amount":4,"target":"any_creature","duration":"permanent","timing":"instant"},{"type":"buff","stat":"hp","amount":4,"target":"any_creature","duration":"permanent","timing":"instant"}],"reaction_trigger":{"event":"opponent_hand_card"}}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Aura 1', 5, 'aura', 1, null, null, 'Ogni volta che la creatura attacca, la creatura ottiene +2/+2', '{"effects":[{"type":"buff","stat":"attack","amount":2,"target":"triggering_creature","duration":"permanent","trigger":"equipped_creature_attacks"},{"type":"buff","stat":"hp","amount":2,"target":"triggering_creature","duration":"permanent","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Aura 3', 5, 'aura', 3, null, null, 'Ogni volta che la creatura attacca, la creatura ottiene +3/+3', '{"effects":[{"type":"buff","stat":"attack","amount":3,"target":"triggering_creature","duration":"permanent","trigger":"equipped_creature_attacks"},{"type":"buff","stat":"hp","amount":3,"target":"triggering_creature","duration":"permanent","trigger":"equipped_creature_attacks"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Terraforma 3', 5, 'terraforma', 3, null, 3, 'Ogni volta che evochi un tuo mostro, quel mostro ottiene +4/+4', '{"effects":[{"type":"buff","stat":"attack","amount":4,"target":"triggering_creature","duration":"permanent","trigger":"own_monster_summoned"},{"type":"buff","stat":"hp","amount":4,"target":"triggering_creature","duration":"permanent","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false),
  (gen_random_uuid(), 'Robustezza · Terraforma 5', 5, 'terraforma', 5, null, 5, 'Ogni volta che evochi un tuo mostro, quel mostro ottiene +5/+5', '{"effects":[{"type":"buff","stat":"attack","amount":5,"target":"triggering_creature","duration":"permanent","trigger":"own_monster_summoned"},{"type":"buff","stat":"hp","amount":5,"target":"triggering_creature","duration":"permanent","trigger":"own_monster_summoned"}]}'::jsonb, null, 0, 'common', '[]'::jsonb, null, null, null, false, false);
end $$;

-- 4) VERIFICA: devono risultare 17 carte per ognuna delle 5 fazioni (85 in tutto).
select f.code as fazione, count(*) as carte,
       count(*) filter (where c.card_type = 'maledizione') as maledizioni,
       count(*) filter (where c.card_type = 'monster') as mostri,
       count(*) filter (where c.card_type = 'instant') as trappole,
       count(*) filter (where c.card_type = 'aura') as aure,
       count(*) filter (where c.card_type = 'terraforma') as terraforme
from public.cards c join public.factions f on f.id = c.faction_id
group by 1 order by 1;

-- DOPO: nell'editor admin, scheda Controllo, premi "Carica l'immagine provvisoria alle 85 carte senza immagine".
-- PER TORNARE INDIETRO (solo se serve): ripristina dalla copia di sicurezza.
--   delete from public.cards;
--   insert into public.cards select * from public.cards_backup_20261006;
--   insert into public.card_subtype_links select * from public.card_subtype_links_backup_20261006;
